### ISSUE TITLE
Leaking Goroutine

### ISSUE THREAD

**Issue by destructive-dragon** [mkenney/go-chrome#101]
### What version of `go-chrome` are you using (tagged commit, commit hash, or `master`)?

84c7e3ff40e5a6d7d05340fe455d00ea4729e638

### What behavior do you expect? What are you trying to accomplish?

Goroutine ending and possibly returning an error somewhere when chrome closes

### What behavior are you experiencing instead?

A goroutine doesn't end after close is being called. Instead it's stuck at the end of `socket.listen` in `github.com/mkenney/go-chrome/tot/socket/socket.socketer.go:361`. Quick glance over the code tells me that the unbuffered error channel isn't being read from at any point and thus the goroutine is stuck indefinitely.

**Comment by mkenney** [comment]
Ahh, thank you. I just changed that, I'll take a look today.

**Comment by mkenney** [comment]
Are you calling `browser.Close()`?

**Comment by mkenney** [comment]
So I think this [`time.After()`](https://github.com/mkenney/go-chrome/blob/master/tot/socket/socket.socketer.go#L463) is the culprit here, when that runs then the goroutine will zombie out. But I also didn't account for the socket going completely quiet either.

I expect that it's taking longer than a second to close the websocket because there isn't any activity. [This](https://github.com/mkenney/go-chrome/pull/102) should cover that case as well. Let me know if you have any other thougts.

**Comment by mkenney** [comment]
Oh, ok, I see, you are correct. It looks like there are two issues. I'll clean that up this morning.
